version: '3'
services:
  app:
    build: .
    volumes:
      - .:/code
    command: bash -c "./main.py"
    environment:
      - LC_ALL=en_US.UTF-8
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US.UTF-8
      - QT_X11_NO_MITSHM=1
